<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Acehole" ignored="6" name="FirstTestModule" tests="3" failures="1" timestamp="10 Jan 2019 05:31:27 GMT" time="0.031" errors="0">
  <testcase name="Demo" time="0.015" classname="testCases.firstTestCase">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.firstTestCase.Demo(firstTestCase.java:25)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- Demo -->
  <testcase name="testCase" time="0.0" classname="testCases.SecondDummyTest"/>
  <testcase name="SecondTest" time="0.0" classname="testCases.firstTestCase">
    <skipped/>
  </testcase> <!-- SecondTest -->
  <testcase name="MobileLogoutHomeLoan2" time="0.0" classname="testCases.FourthDummyTest">
    <ignored/>
  </testcase> <!-- MobileLogoutHomeLoan2 -->
  <testcase name="MobileLoginHomeLoan" time="0.0" classname="testCases.FourthDummyTest">
    <ignored/>
  </testcase> <!-- MobileLoginHomeLoan -->
  <testcase name="LoginAPIHomeLoan" time="0.0" classname="testCases.FourthDummyTest">
    <ignored/>
  </testcase> <!-- LoginAPIHomeLoan -->
  <testcase name="WebLoginHomeLone" time="0.0" classname="testCases.FourthDummyTest">
    <ignored/>
  </testcase> <!-- WebLoginHomeLone -->
  <testcase name="MobileLoginHomeLoan2" time="0.0" classname="testCases.FourthDummyTest">
    <ignored/>
  </testcase> <!-- MobileLoginHomeLoan2 -->
  <testcase name="MobileLogoutHomeLoan" time="0.0" classname="testCases.FourthDummyTest">
    <ignored/>
  </testcase> <!-- MobileLogoutHomeLoan -->
</testsuite> <!-- FirstTestModule -->
